# -*- coding: utf-8 -*-
#
#  Copyright 2008  Luděk Cigler <luc@matfyz.cz>
#  $Id$
#
#  This file is part of SCSPSampler.
# 
#  SCSPSampler is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 3 of the License, or
#  (at your option) any later version.
# 
#  Hollo is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
# 
#  You should have received a copy of the GNU General Public License
#  along with this program. If not, see <http://www.gnu.org/licenses/>.
#

Import('env')

env.Program(target = 'gibbs_sampler', source = Split('gibbs_sampler.cpp utils.cpp csp.cpp celar.cpp'))

env.Default('gibbs_sampler')
