# -*- coding: utf-8 -*-
#
#  Copyright 2008  Luděk Cigler <luc@matfyz.cz>
#  $Id$
#
#  This file is part of SCSPSampler.
# 
#  SCSPSampler is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 3 of the License, or
#  (at your option) any later version.
# 
#  Hollo is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
# 
#  You should have received a copy of the GNU General Public License
#  along with this program. If not, see <http://www.gnu.org/licenses/>.
#

Import('env')

celar_gibbs_node = env.Program(target = 'celar_gibbs', source = Split('celar_gibbs.cpp ../src/utils.cpp \
                                                    ../src/csp.cpp \
                                                    ../src/celar.cpp ../src/gibbs_sampler.cpp'))

ijgp_test_node = env.Program(target = 'ijgp_test', source = Split('ijgp_test.cpp ../src/utils.cpp \
                                                    ../src/csp.cpp \
                                                    ../src/celar.cpp ../src/ijgp.cpp \
                                                    ../src/ijgp_sampler.cpp'))

env.Alias("celar_gibbs", celar_gibbs_node);
env.Alias("ijgp_test", ijgp_test_node);

